spring:
  datasource:
    url: jdbc:mysql://localhost:3306/annual_management
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.example.miniproject: DEBUG
    org.hibernate.type: TRACE

AES:
  secretKey: ${{AES_KEY}}

jwt:
  issuer: ${{JWT_ISSUER}}
  secret_key: ${{JWT_KEY}}