server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://${DB.HOSTNAME}:${DB.PORT}/${DB.NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
  data:
    redis:
      host: ${REDIS.HOSTNAME}
      port: ${REDIS.PORT}

logging:
  level:
    com.example.miniproject: INFO

AES:
  secretKey: ${AES.SECRET}

jwt:
  issuer: ${JWT.ISSUER}
  secret_key: ${JWT.SECRET}



