server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      default_batch_fetch_size: 100
    open-in-view: false
logging:
level:
  com.example.miniproject: DEBUG

AES:
  secretKey: ${AES_KEY}

jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_KEY}